# Generated by Django 5.0.1 on 2026-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("recruiter", "Recruiter"),
                    ("candidate", "Candidate"),
                ],
                default="recruiter",
                max_length=50,
            ),
        ),
    ]
